name: 
  'mail-service'

volumes:
  mail-service-database-data:
    driver: local

services:
  database:
    image: 'postgres:17.2'
    restart: 'unless-stopped'

    container_name: database

    volumes:
      - 'mail-service-database-data:/var/lib/postgresql/data'

    environment:
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'

    ports:
      - '${DATABASE_PORT}:5432'

  mail-server:
    build:
      context: './docker/mail-server/'
      args:
        DATABASE_PASSWORD: '${DATABASE_PASSWORD}'

    restart: 'on-failure:3'

    container_name: 'mail-server'
    hostname: 'mail-server.local'

    depends_on:
      database:
        condition: service_started

    ports:
      - '587:587'